language: node_js

node_js:
    - 'stable'
  
  services:
    - mongodb
  
  script:
    - npm ci
    - npm run coverage
  
  notifications:
    email: false
  
  after_success:
    - npm run coveralls
  